Repository aldaitzwild/WCS_Pull_Request_Tracker, pull requests merged in 2023-06, with the labels that each got.

#27 Detail view of a project to be reorganized
  src/Controller/ProjectController.php
  templates/project/show.html.twig
Labels: Changes done

#29 fixed buttons and font size
  assets/styles/_styles.scss
  templates/contributor/_form.html.twig
  templates/contributor/index.html.twig
  templates/contributor/show.html.twig
  templates/project/_form.html.twig
  templates/project/index.html.twig
  templates/project/show.html.twig
  templates/pull_request/show.html.twig
Labels: Changes done

#35 S 01 30 authentification standard pour les users
  assets/scripts/ajaxModalSearch.js
  assets/styles/_styles.scss
  config/packages/security.yaml
  migrations/Version20230607133412.php
  src/Controller/AjaxController.php
  src/Controller/ContributorController.php
  src/Controller/HomeController.php
  src/Controller/ProjectController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/AppUserAuthenticator.php
  templates/base.html.twig
  templates/component/_sideNav.html.twig
  templates/home/index.html.twig
  templates/security/login.html.twig
  yarn.lock
Labels: Need pair review

#40 Fix: Search a contributor
  assets/scripts/ajaxModalSearch.js
Labels: Need pair review

#37 add pullrequest fixtures and display the pr list of all projects
  src/Controller/PullRequestController.php
  src/DataFixtures/ContributorFixtures.php
  src/DataFixtures/PullRequestFixtures.php
  src/Entity/PullRequest.php
  templates/component/_sideNav.html.twig
  templates/contributor/index.html.twig
  templates/contributor/show.html.twig
  templates/project/index.html.twig
  templates/project/show.html.twig
  templates/pull_request/index.html.twig
  templates/pull_request/show.html.twig
Labels: Changes done

#47 31 service de synchronisation des projets pour alimentation en base
  composer.json
  composer.lock
  migrations/Version20230615084452.php
  src/Controller/AjaxController.php
  src/Controller/ContributorController.php
  src/Controller/GithubAuthController.php
  src/Controller/ProjectController.php
  src/Controller/PullRequestController.php
  src/Entity/PullRequest.php
  src/Repository/ProjectRepository.php
  src/Repository/PullRequestRepository.php
  src/Security/AppUserAuthenticator.php
  src/Service/FetchGithubService.php
  src/Service/GithubOauth2.php
Labels: Changes done

#51 detail view of a project to be reorganized and add a pullrequest manager
  migrations/Version20230614102508.php
  src/Controller/ProjectController.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/PullRequestFixtures.php
  src/Entity/Project.php
  src/Service/PullRequestManager.php
  templates/project/show.html.twig
Labels: Changes done

#55 small fixes
  src/Controller/ProjectController.php
  src/Repository/PullRequestRepository.php
  templates/project/index.html.twig
  templates/project/show.html.twig
Labels: Changes done

#56 S2 50 style de la vue des pr
  assets/styles/_styles.scss
  src/Controller/PullRequestController.php
  src/Repository/PullRequestRepository.php
  templates/contributor/index.html.twig
  templates/contributor/show.html.twig
  templates/project/index.html.twig
  templates/project/show.html.twig
  templates/pull_request/index.html.twig
  templates/pull_request/show.html.twig
Labels: Changes done

#52 33 service de synchronisation des pr pour alimentation en base
  migrations/Version20230615135645.php
  migrations/Version20230619162723.php
  src/Controller/PullRequestController.php
  src/Entity/PullRequest.php
  src/Repository/ProjectRepository.php
  src/Repository/PullRequestRepository.php
  src/Service/FetchGithubService.php
  templates/project/show.html.twig
  templates/pull_request/index.html.twig
  templates/pull_request/show.html.twig
Labels: Changes done, Conflicts Resolved

#64 S3-display the oldest open prs first
  src/Repository/PullRequestRepository.php
  templates/contributor/show.html.twig
  templates/project/show.html.twig
Labels: Changes done
